### PR TITLE
Add Google Gemini API Support

### PR DESCRIPTION
**Pull request by toandev95**
Contribute code that supports the Google Gemini API.
https://github.com/google-gemini/generative-ai-js#readme

### CODE REVIEW

**Review by julien-c — COMMENTED** [review]
cool contribution, @toandev95!

**Review by nsarrazin — CHANGES_REQUESTED** [review]
Hi, thanks for the contrib, would be very happy to merge it! Couple things that I think need updating:
* Could we expand the doc in `google.md` a bit to explain the difference with the vertex endpoints, and explain how to use it a bit more ?
* Could we make `@google/generative-ai` an optional dependency like [the other providers](https://github.com/huggingface/chat-ui/blob/5cc88e4c10d0040452575b396ccd8faa815f88a3/package.json#L102-L109) ?

Other than that lgtm!

**Comment by toandev95** [comment]
> Hi, thanks for the contrib, would be very happy to merge it! Couple things that I think need updating:
> 
> * Could we expand the doc in `google.md` a bit to explain the difference with the vertex endpoints, and explain how to use it a bit more ?
> * Could we make `@google/generative-ai` an optional dependency like [the other providers](https://github.com/huggingface/chat-ui/blob/5cc88e4c10d0040452575b396ccd8faa815f88a3/package.json#L102-L109) ?
> 
> Other than that lgtm!

Thank you @nsarrazin, is there any chance you could take a look at my latest commit? Feel free to let me know if you have any additional comments

**Review by nsarrazin — APPROVED** [review]
Looks great! Thanks for contributing

**Pull request merged**
