### PR TITLE
Fix OpenAI Embeddings Auth Issue

### PR DESCRIPTION
**Pull request by adhishthite**
Fixing this issue: https://github.com/huggingface/chat-ui/issues/1072

OpenAI depends on `Api-Key` instead of `Authorization`

### CODE REVIEW

**Comment by nsarrazin** [comment]
Hey thanks for contributing a PR! I'm a bit surprised, looking at the [OpenAI doc](https://platform.openai.com/docs/api-reference/authentication) it looks like they use `Authorization`... Could it be an azure specific thing ?

In which case, I think the easiest thing would be to follow the [OpenAI endpoint for text generation](https://github.com/huggingface/chat-ui/blob/745e51e28bab8c380564efb32056a3508ee94f11/src/lib/server/endpoints/openai/endpointOai.ts#L17-L19) and add options for `defaultHeaders` and `defaultQuery` in the embedding endpoint.

Let me know if that sounds like something you can/want to do, otherwise I'll open a PR :smile:

**Comment by adhishthite** [comment]
@nsarrazin Thanks! I will do this. Give me a day. It's almost 3:00 AM here, I'll do it once I resume work tomorrow.

**Comment by adhishthite** [comment]
This seems like an Azure only thing.

**Comment by adhishthite** [comment]
@nsarrazin 

How about I create a new `type` altogether for Azure OpenAI? Since the Auth and the URL type is different, (and might change in the future), having a new `azure-openai` type for embeddings will be much easier to modify and manage.

Please lmk what you think.

**Comment by nsarrazin** [comment]
Hey @adhishthite I'd be more in favour of just adding a `defaultHeaders` option like [here](https://github.com/huggingface/chat-ui/blob/745e51e28bab8c380564efb32056a3508ee94f11/src/lib/server/endpoints/openai/endpointOai.ts#L17)

Then you can do

```
					headers: {
						Accept: "application/json",
						"Content-Type": "application/json",
						...(apiKey ? { Authorization: `Bearer ${apiKey}` } : {}),
                                                ...defaultHeaders
                                                }
```

something like this, which should be enough for your auth needs I think :grin:

**Comment by nsarrazin** [comment]
I pushed a commit to your branch, where I added the `defaultHeaders` option in the endpoint.

You should be able to make it work with azure by adding 
```
"defaultHeaders" : {
    "Api-Key" : "your api key"
}
```

to your embedding endpoint config. Let me know if that works!

**Comment by nsarrazin** [comment]
going to merge this, let me know if it needs something else!

**Review by nsarrazin — APPROVED** [review]

**Pull request merged**
