### PR TITLE
Fix model identification when creating conversations

### PR DESCRIPTION
**Pull request by zacps**
PR #181 introduced a model ID field so that models could be switched out without breaking existing conversations. However, the new conversation endpoint incorrectly uses the model name instead of ID, so without this fix it was not possible to have a model with a different ID and name.

### CODE REVIEW

**Comment by nsarrazin** [comment]
Hi, thanks for the contribution! I'm not sure I fully understand what the code is supposed to do here. Could you give an example of an issue you were having that this solves?

I could imagine scenarios where `(m.id ?? m.name) === values.model);
` or ` m.id === values.model || m.name === values.model` would make sense but wouldn't `m.id || m.name === values.model` just return the first model with non-null ID?

**Comment by zacps** [comment]
Yes! Thanks for catching that, I made mistake with precedence; fixed :).

I think `(m.id ?? m.name) === values.model);` and `(m.id || m.name) === values.model);` are functionally equivalent here but happy to use one over the other if you prefer.

Currently if you have a model configured with a different id and name, for example something like:

```
   {
      "id": "gpt-4-1106-preview",
      "name": "gpt-4",
      "displayName": "GPT 4 Turbo",
      "endpoints" : [{
         "type": "openai" ,
      }]
   },
```

You won't be able to create any conversations because the client sends the model id, `gpt-4-1106-preview`, and the server only searches the model names `["gpt-4"]`.

**Comment by zacps** [comment]
@nsarrazin do you think you'll have a chance to review this soon? This is the last PR keeping us on a fork.

**Review by nsarrazin — APPROVED** [review]

**Comment by nsarrazin** [comment]
Finally got around to reviewing this sorry! Will merge it now, thanks for the contrib @zacps :rocket:

**Pull request merged**
