### PR TITLE
Added husky for pre committing.

### PR DESCRIPTION
**Pull request by krakenftw**
Added husky as well as pre commit script to lint it. Let me know if we can extend it more? maybe adding testing before commit. #1317

### CODE REVIEW

**Comment by krakenftw** [comment]
Also we need to make sure this does not run in CI. So adding `HUSKY: 0` as ENV in CI pipeline, husky wont work there.

**Comment by krakenftw** [comment]
@nsarrazin Any updates on this?

**Review by nsarrazin — APPROVED** [review]
Thanks for the contrib! PR looking good, I fixed the build errors and merge conflicts but should be good to merge now.

**Comment by krakenftw** [comment]
Perfect, thanks for the merge : )

**Pull request merged**
