### PR TITLE
Sort by Trending to default

### PR DESCRIPTION
**Pull request by KingNishHF**
Switched the default sorting from 'popular' to 'trending'.

WHY?? : Because everything on hugging face as default sort by trending

### CODE REVIEW

**Comment by nsarrazin** [comment]
cc @mishig25 @gary149 this makes sense to me, I also think we'll see more variety in assistants if trending is shown by default

**Review by gary149 — APPROVED** [review]
ok for me

**Review by nsarrazin — APPROVED** [review]
Committed a change to apply the change in the load function too, seems to work now!

**Comment by nsarrazin** [comment]
Thanks for the contribution! :rocket:

**Comment by KingNishHF** [comment]
> Thanks for the contribution! 🚀

Currently it's not working.
I think something more needed to be change on because default not changed.

**Pull request merged**
