### PR TITLE
(Feature): LLM routing integration via NotDiamond

### PR DESCRIPTION
**Pull request by barabasicsongor**
## Overview

Hi there! I am a big fan of `HuggingChat` and would love to integrate Not Diamond into it. In case you're unfamiliar with Not Diamond, it automatically routes your prompts to the AI model best-suited to respond to that prompt. By using Not Diamond as an AI "meta-model," you can achieve state-of-the-art performance that beats every foundation model on every major benchmark.*

For `HuggingChat` we would like to integrate our router into your app as a "meta-model," so that users can automatically route their prompts without toggling different models.

## Description of approach

We have integrated NotDiamond as a new model in the list of supported models on HuggingChat.
The router currently supports routing across the following 3 models:
- Qwen/Qwen2.5-72B-Instruct
- meta-llama/Meta-Llama-3.1-70B-Instruct
- mistralai/Mistral-Nemo-Instruct-2407

Whenever a user selects the NotDiamond model, behind the scenes we will call the NotDiamond LLM router to decide the best of the above 3 models to call, and afterwards we'll execute the LLM call.

Screenshots:
Screenshot 2024-10-21 at 19 53 02

Screenshot 2024-10-21 at 19 54 19

## Before deployment

Before deploying this feature, the following configuration has to be added to the **MODELS** array in the `.env` file.

```
{
  "name": "notdiamond/autoselect",
  "displayName": "notdiamond/autoselect",
  "description": "Not Diamond is a model router. It will route between Meta-Llama-3.1-70B-Instruct, Qwen2.5-72B-Instruct, Mistral-Nemo-Instruct-2407 on HuggingChat. To route to more models, check out our docs.",
  "websiteUrl": "https://www.notdiamond.ai/",
  "preprompt": "",
  "modelUrl":"https://docs.notdiamond.ai/",
  "logoUrl": "https://cdn.prod.website-files.com/64b9c0f00a5b6bdf6393396c/6638d2edf7c92e93fb964067_logo%20(1).svg",
  "chatPromptTemplate" : "<s>{{#each messages}}{{#ifUser}}[INST] {{#if @first}}{{#if @root.preprompt}}{{@root.preprompt}}\n{{/if}}{{/if}}{{content}} [/INST]{{/ifUser}}{{#ifAssistant}}{{content}}</s>{{/ifAssistant}}{{/each}}",
  "llmProviders":[
    { provider: 'togetherai', model: 'Meta-Llama-3.1-70B-Instruct-Turbo' },
    { provider: 'togetherai', model: 'Qwen2-72B-Instruct' },
    { provider: 'mistral', model: 'open-mistral-nemo' },
  ],
  "endpoints": [{"type": "notdiamond", "model":"notdiamond"}],
  "promptExamples": [
    {
      "title": "What is the diamond operator in modal logic?",
      "prompt": "What is the diamond operator in modal logic?"
    }, {
      "title": "Write a merge sort in Python",
      "prompt": "Write a merge sort in Python."
    }, {
      "title": "Compose a sonnet about open source AI",
      "prompt": "Compose a sonnet about open source AI"
    }
  ]
}
```

Also a `NOTDIAMOND_API_KEY` should be added. Please reach out to t5@notdiamond.ai so we can share one securely with your team.

## Other relevant notes

*If you’d like to learn more about our routing, check out [this example walkthrough video with Tomas](https://x.com/tomas_hk/status/1818296673749328199), our CEO. You can also
see how we work by using [our Chat app](https://chat.notdiamond.ai/),
learn more at [our website](https://www.notdiamond.ai/), or
[read our docs](https://notdiamond.readme.io/).

### CODE REVIEW

**Comment by nsarrazin** [comment]
Hi! This looks very cool, thanks for the PR. Could you clarify if it's possible to host your own router using this or if it's only using the hosted services from NotDiamond?

**Comment by barabasicsongor** [comment]
> Hi! This looks very cool, thanks for the PR. Could you clarify if it's possible to host your own router using this or if it's only using the hosted services from NotDiamond?

Hey @nsarrazin ! Self hosting is possible but would require a considerable amount of engineering effort as our backend is much more complicated than a single model. For this integration it would be best to use our API.

I'm going to fix the PR conflicting files now, and then let me know if it's all good to go 😄

**Comment by barabasicsongor** [comment]
Hey @nsarrazin , wanted to follow up here, would this PR be good to be accepted and shipped to production? 😄 

If yes, then we can provide you a NotDiamond API key that you can use on your end. Please drop us an email at t7@notdiamond.ai 🙏

**Comment by nsarrazin** [comment]
Hi! We're trying to move away from vendor specific endpoints so I'll be closing this PR at this time. 

I would love to properly support routing in the future but it would need more thought to show the user what models are available, which one was chosen, etc. and not be locked-in to any particular solution.

**Pull request closed without merging**
