### PR TITLE
Feat: Delete branch #1210

### PR DESCRIPTION
**Pull request by krakenftw**
Fixes https://github.com/huggingface/chat-ui/issues/1210

Added a deleteBranch action along with button which appears on messages with multiple branches only, When clicked it deletes the message and the related ancestors and children as well.
Here are the picture -
image
After clicking the Trash Icon,
image
It goes back to previous branch.

### CODE REVIEW

**Comment by krakenftw** [comment]
@nsarrazin please review this? I think its working fine but would like to know anything left/improvements.

**Review by nsarrazin — APPROVED** [review]
Hi @krakenftw ! Thanks for the contribution. :fire: 

 I've made a couple changes to the PR, let me know what you think:
* I find the conversation directly using the conversation._id (since before we were iterating over every conv to find the message id, which could be quite slow when the DB is big)
* I rewrote the filtering a bit and added an auth check to make sure someone can't delete other people's branches
* I changed the icon styling a bit to make it more aligned with the rest of the UI

Overall this looks good to me!

**Comment by nsarrazin** [comment]
cc @gary149 for styling check

**Comment by gary149** [comment]
Not sure we want to be able to delete a branch, it could be confusing + make the UI more complex. Maybe this could be config option (disabled by default).

**Comment by nsarrazin** [comment]
I think the feature has been requested quite a lot, also for HuggingChat:

* [here](https://huggingface.co/spaces/huggingchat/chat-ui/discussions/369#65ce6bcb0d5f3249c608d486)
* [here](https://huggingface.co/spaces/huggingchat/chat-ui/discussions/369#65cf004f3560eb81f1eda4ea)
* [this discussion](https://huggingface.co/spaces/huggingchat/chat-ui/discussions/464)
* and #1210 

I agree that it adds complexity/visual bloat though. Maybe it should only show on hover when navigating between branches? (the other buttons for retrying, etc. are also on hover only)

**Comment by gary149** [comment]
Ok to make it appear when you hover the arrow group.

**Review by gary149 — APPROVED** [review]

**Comment by krakenftw** [comment]
Hey, @nsarrazin, Thanks for the review and improvements.
was my first time doing open source and i absolutely love the support you guys gave, looking forward to do it more often.

**Pull request merged**
