### PR TITLE
Add langserve endpoint

### PR DESCRIPTION
**Pull request by antonioramos1**
Hey thanks for sharing chat-ui with the community! We have been using it for a while and would now like to contribute to continue making it great :)

LangServe is the go-to service for deploying LLM applications built using LangChain. Supporting this type of endpoint opens the door to using new Models in chat-ui that are powered up for example by using custom chains on top of an LLM.

Note, I am pretty new to Javascript so I am open to any feedback on the code !

### CODE REVIEW

**Comment by nsarrazin** [comment]
Thanks for the contribution! Will take a look, would be nice to support langserve 😁

**Review by nsarrazin — APPROVED** [review]
Thanks for the contribution! :fire:

**Comment by antonioramos1** [comment]
Amazing thanks! May I ask if it's possible to trigger a release so we can benefit from this feature? :)

**Comment by nsarrazin** [comment]
@antonioramos1 should be good!

**Pull request merged**
