### PR TITLE
Make all prompt templates configurable

### PR DESCRIPTION
**Pull request by AndreasMadsen**
This PR enables all prompts to be configurable using handlebar templates as described in #382.

For backward compatibility the old hardcoded templates are reimplemented as the default templates. The old template parameters such as `preprompt`, `userMessageToken`, `userMessageEndToken`, `assistantMessageToken`, `assistantMessageEndToken` are now considered legacy. They still work as they are exposed as variables to the default
template. However, new prompt configurations should not use these. And it is recommended that the legacy support is eventually removed.

As an example, this is how the default chat prompt template is implemented:

```
{{preprompt}}
{{#each messages}}
{{#ifUser}}{{@root.userMessageToken}}{{content}}{{@root.userMessageEndToken}}{{/ifUser}}
{{#ifAssistant}}{{@root.assistantMessageToken}}{{content}}{{@root.assistantMessageEndToken}}{{/ifAssistant}}
{{/each}}
{{assistantMessageToken}}
```

In addition, this PR fixes an issue where the `model` configuration was used to generate the prompts in WebSearch. However, the `defaultModel` was used to query. This caused issues when the `model` and `defaultModel` uses
different prompt configurations. This has now been changed to always use the `defaultModel`.

Note, when developing this PR, it has been observed that the WebSearch prompts can violate typical model assumptions. For example, a query may be generated as:

```
Assistant: The following context ...
User: content ...
```

```
User: user message 1
User: user message 2
Assistant:
```

Models typically assume the prompts to be User -> Assistant -> User. For best compatability with existing configurations, this issues was not fixed. Instead, the old behavior is maintained with the default templates. This is also the reason why `defaultModel` was chosen as the WebSearch model instead of `model`. As `defaultModel` may allow the WebSearch format, while `model` might not.

This behavior, as well as the overall aritecture of chat-ui, necessitated that the template input maintained the format

```
messages: [{from: 'user' | 'assistant', content: string }]
```

For the template to be able to detect which source a message comes from a `ifUser` and a `ifAssistant` handlebar block-helper was implemented. The original proposed format in #382 was:

```
history: [{ user: string, assistant: string }]
```

However, using such format would require significant changes to the project and would make it impossible to implement the existing websearch templates.

Finally, there may be minor differences in how truncation is implemented. As in some cases, truncation is now applied to the entire prompt, rather than part of the prompt.

Fixes: #382

### CODE REVIEW

**Comment by nsarrazin** [comment]
:fire: Thanks for doing this, it looks great. I'll have a look at it and I hope we can combine it with #399 !

**Comment by AndreasMadsen** [comment]
@nsarrazin Should be quite trivial to combine. The template already support a `preprompt` parameter.

**Comment by nsarrazin** [comment]
Thanks, this is looking pretty good!

I'm using this template for llama2: 

```
"<s>[INST] <<SYS>>\n{{preprompt}}<</SYS>>\n\n{{#each messages}}{{#ifUser}}{{content}} [/INST] {{/ifUser}}{{#ifAssistant}}{{content}} </s><s>[INST] {{/ifAssistant}}{{/each}}"
```

It seems to work quite well. This is a great PR that's going to make things super flexible moving forward. Really appreciate the work done here!

**Comment by julien-c** [comment]
thanks for this PR @AndreasMadsen it is very cool!

**Pull request merged**
