### PR TITLE
added svg favicon and updated link

### PR DESCRIPTION
**Pull request by digitaljerrygit**
Left the original favicon.png. Added the SVG provided and updated link.

### CODE REVIEW

**Comment by coyotte508** [comment]
Related to #203

**Comment by coyotte508** [comment]
@Grsmto does it work with Safari? https://caniuse.com/link-icon-svg

**Comment by coyotte508** [comment]
Seems a mask-icon needs to be added for safari: https://medium.com/swlh/are-you-using-svg-favicons-yet-a-guide-for-modern-browsers-836a6aace3df

**Comment by Grsmto** [comment]
No Safari it doesn't work but it should fallback to the .png fine!
The mask-icon thing is only used on the touch bar on the old macbooks I think 😅  probably not necessary tbh.

**Review by Grsmto — APPROVED** [review]

**Comment by Grsmto** [comment]
Thanks @digitaljerrygit !

**Pull request merged**
