### PR TITLE
Enhance Dynamic User Attribute Handling in OIDC Integration

### PR DESCRIPTION
**Pull request by mcc311**
Add `nameClaim` in `.env` for those OpenID Provider which don't use `name` as default identifier.

### CODE REVIEW

**Comment by mcc311** [comment]
@nsarrazin Sorry for the prettier problem. I have pushed a newer version fixing this problem.

**Comment by nsarrazin** [comment]
No worries! Am reviewing the PR itself and it looks good, I'll fix any linting problems if there are any 😄

**Comment by nsarrazin** [comment]
@mcc311 Sorry for the delay! I changed a few things in [c0d98cf](https://github.com/huggingface/chat-ui/pull/885/commits/c0d98cf0abc16a3fd7309c059c1627d8cda6e949) and [bc25544](https://github.com/huggingface/chat-ui/pull/885/commits/bc25544209e73cca8f54de210452a029c7cd0302), if the feature still works for you then I think we could merge this :smile:

**Review by mcc311 — COMMENTED** [review]
Yeah, I think the change is great!

**Review by nsarrazin — APPROVED** [review]
Thanks for the contribution! Will merge this right after 🚀

**Pull request merged**
