### PR TITLE
Disable text streaming if user prefers reduced animation

### PR DESCRIPTION
**Pull request by neven4**
Disable the streaming updates when `prefers-reduced-motion` is set to `reduce`

Closes: https://github.com/huggingface/chat-ui/issues/684

### CODE REVIEW

**Comment by neven4** [comment]
Hi @nsarrazin, kindly requesting a review

**Comment by neven4** [comment]
Hi @coyotte508, @gary149, @mishig25 maybe you could do a review?

**Comment by nsarrazin** [comment]
Hi! Thanks for a great contrib 🔥 I took the liberty to push a commit that simplifies the way you filter stream updates in `src/routes/conversation/[id]/+page.svelte` 

But overall it works great in local testing, if my fix still works for you then we can merge this!  🚀

**Review by nsarrazin — APPROVED** [review]

**Review by skarvsladd — COMMENTED** [review]
Great catch on addressing this animation preference! Reducing motion for users who prefer a more static experience is a thoughtful touch. The changes made in this pull request seem well-structured and on-point. The addition of the 'isReduceMotion' utility function is a clever way to respect users' preferences and ensure an enjoyable experience. Keep an eye on potential edge cases and browser compatibility, but overall, this looks like a solid implementation. Nice work!

**Pull request merged**
