### PR TITLE
Switch task model to mistral 7b v0.2

### PR DESCRIPTION
**Pull request by nsarrazin**

### CODE REVIEW

**Comment by gary149** [comment]
is it working well?

**Comment by nsarrazin** [comment]
> is it working well?

Now that the v0.1 endpoint is back up, we don't _need_ this.

Would be nice to find a more recent model for the task model though, as mistral v0.1 is deprecated in the UI and only used for tasks now

**Comment by mishig25** [comment]
> Would be nice to find a more recent model for the task model though, as mistral v0.1 is deprecated in the UI and only used for tasks now

I will test gemma for the task

**Comment by nsarrazin** [comment]
We can reopen something when we switch,closing for now :smile:

**Pull request closed without merging**
