### PR TITLE
Add PDF to Markdown feature

### PR DESCRIPTION
**Pull request by julien-blanchon**
This pull request introduces the PDF to Markdown conversion. This enhancement aims to provide users with a seamless experience when discussing and referencing content from PDFs, especially in academic and research contexts.

### CODE REVIEW

**Comment by nsarrazin** [comment]
Very cool idea! I'll do a deeper review later but thanks for contributing already 😄

**Comment by julien-blanchon** [comment]
> Very cool idea! I'll do a deeper review later but thanks for contributing already 😄

Great, I write a more detailed issues about this [here](https://github.com/huggingface/chat-ui/issues/441).

It seems that I got some problem with my fork branch, look like I wasn't update at time of the PR.
I will fix that soon. 

If you figure out any inconsistencies with the code base or just typescript/svelte bad practice feel free to comment or propose a fix.
This features was originaly code for my personal usage but I think this could be usefull for everyone, in particular for research paper this worflow of converting the file to native markdown/latex give impressive result with GPT4 and Claude2.

I also did a PR about adding the OpenAI API support in Chat UI [here](https://github.com/huggingface/chat-ui/pull/443).

**Comment by hungryalgo** [comment]
@julien-blanchon 
Adding file support, especially PDF is such an important feature, are you going to merge this later? What is the mostly current branch that this is worked on? I see #449. 

I do not see that [agent](https://github.com/huggingface/chat-ui/tree/agents) branch end up using the file drop UI.

Just any updates on how we want to go from here is nice. Why is this PR dropped? I would love to see this merged to main.

thanks! very nice to see this.

**Comment by julien-blanchon** [comment]
@hungryalgo 
https://github.com/huggingface/chat-ui/pull/449 is outdated. Yes, having the PDF in the chat interface would be very cool. As far as I know, there are no plans for that yet. However, I have suggested the idea of doing a basic PDF integration in chat-ui (without the Mathpix stuff): https://github.com/huggingface/chat-ui/pull/531#issuecomment-1781352008.

I don't know if there are any plans to add the PDF soon, @nsarrazin might be the best person to ask

**Comment by jackbravo** [comment]
Closed in favor of PR #641 that closes issue #609, right?

**Pull request closed without merging**
