### PR TITLE
Use `@postlight/parser` for parsing html text

### PR DESCRIPTION
**Pull request by mishig25**
Comparing HTML text parsers:
* jsdom (parse only `<p>` elements) (current approach)
* https://github.com/mozilla/readability
* https://github.com/postlight/parser

From the tests below, that you can see https://github.com/postlight/parser is producing slightly better results. Please let me know what you think of these prompt tests on different parsers

Find all the data of prompts and generations: <a href="https://docs.google.com/spreadsheets/d/1pNoDa00d-yoOQt5SwVczDeOO8atsbY3YTK002FwUIPU/edit#gid=719616982"> Google Sheet image </a>

### CODE REVIEW

**Comment by gururise** [comment]
Very interesting. It does appear that the postlight/parser did give better results for the "**Who won the US Open?**" question.

Might be beneficial to test on a few more questions, specifically related to product searches, as that is also quite a common use case.

**Comment by mishig25** [comment]
@gururise if you have some good questions to test, please comment them below 👍

**Comment by gururise** [comment]
> @gururise if you have some good questions to test, please comment them below 👍

Sorry, here are a few questions that I came up with over the weekend:

1. What is the print width of the Prestige A4 DTF printer?  (answer: 7.87")
2. Does the DigiRIP RIP Software only run on windows? (answer: yes, windows only)
3. How many print heads does the Prestige R2 DTF printer have? (answer: 2 Epson L805 print heads)
4. What type of printhead does the Epson F2270 DTG printer use? (answer: PrecisionCore MicroTFP printhead with Nozzle Verification Technology)

These are all equipment that are new and won't be in any LLM's knowledge. Hope this helps!

**Comment by mishig25** [comment]
Thanks so much. Will test on them

**Comment by nsarrazin** [comment]
@mishig25 just curious, do you think we should switch parsers in the end? (And does this PR overlap with the changes in #502 ?)

**Comment by mishig25** [comment]
Indeed. this PR is superceded by #502

**Pull request closed without merging**
